// <auto-generated/>
#pragma warning disable CS0618
using Helo.ApiClient.Activity.Statistics.Daily;
using Helo.ApiClient.Activity.Statistics.Hourly;
using Helo.ApiClient.Activity.Statistics.Totals;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Helo.ApiClient.Activity.Statistics
{
    /// <summary>
    /// Builds and executes requests for operations under \activity\statistics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatisticsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The daily property</summary>
        public global::Helo.ApiClient.Activity.Statistics.Daily.DailyRequestBuilder Daily
        {
            get => new global::Helo.ApiClient.Activity.Statistics.Daily.DailyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hourly property</summary>
        public global::Helo.ApiClient.Activity.Statistics.Hourly.HourlyRequestBuilder Hourly
        {
            get => new global::Helo.ApiClient.Activity.Statistics.Hourly.HourlyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The totals property</summary>
        public global::Helo.ApiClient.Activity.Statistics.Totals.TotalsRequestBuilder Totals
        {
            get => new global::Helo.ApiClient.Activity.Statistics.Totals.TotalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Activity.Statistics.StatisticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatisticsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/activity/statistics", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Activity.Statistics.StatisticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatisticsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/activity/statistics", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
