// <auto-generated/>
#pragma warning disable CS0618
using Helo.ApiClient.Activity;
using Helo.ApiClient.Channels;
using Helo.ApiClient.Domains;
using Helo.ApiClient.Send;
using Helo.ApiClient.WebhookEndpoints;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Helo.ApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HeloApiClient : BaseRequestBuilder
    {
        /// <summary>The activity property</summary>
        public global::Helo.ApiClient.Activity.ActivityRequestBuilder Activity
        {
            get => new global::Helo.ApiClient.Activity.ActivityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The channels property</summary>
        public global::Helo.ApiClient.Channels.ChannelsRequestBuilder Channels
        {
            get => new global::Helo.ApiClient.Channels.ChannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The domains property</summary>
        public global::Helo.ApiClient.Domains.DomainsRequestBuilder Domains
        {
            get => new global::Helo.ApiClient.Domains.DomainsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The send property</summary>
        public global::Helo.ApiClient.Send.SendRequestBuilder Send
        {
            get => new global::Helo.ApiClient.Send.SendRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhookEndpoints property</summary>
        public global::Helo.ApiClient.WebhookEndpoints.WebhookEndpointsRequestBuilder WebhookEndpoints
        {
            get => new global::Helo.ApiClient.WebhookEndpoints.WebhookEndpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.HeloApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HeloApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "http://localhost:8000";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
