// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Helo.ApiClient.Channels
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetDeliveryTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "live")]
        #pragma warning disable CS1591
        Live,
        #pragma warning restore CS1591
        [EnumMember(Value = "blackhole")]
        #pragma warning disable CS1591
        Blackhole,
        #pragma warning restore CS1591
        [EnumMember(Value = "routed")]
        #pragma warning disable CS1591
        Routed,
        #pragma warning restore CS1591
    }
}
