// <auto-generated/>
#pragma warning disable CS0618
using Helo.ApiClient.Send.Broadcast;
using Helo.ApiClient.Send.Transactional;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Helo.ApiClient.Send
{
    /// <summary>
    /// Builds and executes requests for operations under \send
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SendRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The broadcast property</summary>
        public global::Helo.ApiClient.Send.Broadcast.BroadcastRequestBuilder Broadcast
        {
            get => new global::Helo.ApiClient.Send.Broadcast.BroadcastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactional property</summary>
        public global::Helo.ApiClient.Send.Transactional.TransactionalRequestBuilder Transactional
        {
            get => new global::Helo.ApiClient.Send.Transactional.TransactionalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Send.SendRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/send", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Send.SendRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/send", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
