// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Helo.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DnsRecordType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "txt")]
        #pragma warning disable CS1591
        Txt,
        #pragma warning restore CS1591
        [EnumMember(Value = "cname")]
        #pragma warning disable CS1591
        Cname,
        #pragma warning restore CS1591
    }
}
