// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Helo.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DnsRecordsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The domainKeyActive property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.DnsRecordResponse? DomainKeyActive { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.DnsRecordResponse DomainKeyActive { get; set; }
#endif
        /// <summary>The domainKeyPending property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.DnsRecordResponse? DomainKeyPending { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.DnsRecordResponse DomainKeyPending { get; set; }
#endif
        /// <summary>The returnPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.DnsRecordResponse>? ReturnPath { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.DnsRecordResponse> ReturnPath { get; set; }
#endif
        /// <summary>The tracking property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.DnsRecordResponse? Tracking { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.DnsRecordResponse Tracking { get; set; }
#endif
        /// <summary>The unsubscribe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.DnsRecordResponse? Unsubscribe { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.DnsRecordResponse Unsubscribe { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Models.DnsRecordsResponse"/> and sets the default values.
        /// </summary>
        public DnsRecordsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Helo.ApiClient.Models.DnsRecordsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Helo.ApiClient.Models.DnsRecordsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Helo.ApiClient.Models.DnsRecordsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "domainKeyActive", n => { DomainKeyActive = n.GetObjectValue<global::Helo.ApiClient.Models.DnsRecordResponse>(global::Helo.ApiClient.Models.DnsRecordResponse.CreateFromDiscriminatorValue); } },
                { "domainKeyPending", n => { DomainKeyPending = n.GetObjectValue<global::Helo.ApiClient.Models.DnsRecordResponse>(global::Helo.ApiClient.Models.DnsRecordResponse.CreateFromDiscriminatorValue); } },
                { "returnPath", n => { ReturnPath = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.DnsRecordResponse>(global::Helo.ApiClient.Models.DnsRecordResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tracking", n => { Tracking = n.GetObjectValue<global::Helo.ApiClient.Models.DnsRecordResponse>(global::Helo.ApiClient.Models.DnsRecordResponse.CreateFromDiscriminatorValue); } },
                { "unsubscribe", n => { Unsubscribe = n.GetObjectValue<global::Helo.ApiClient.Models.DnsRecordResponse>(global::Helo.ApiClient.Models.DnsRecordResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Helo.ApiClient.Models.DnsRecordResponse>("domainKeyActive", DomainKeyActive);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.DnsRecordResponse>("domainKeyPending", DomainKeyPending);
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.DnsRecordResponse>("returnPath", ReturnPath);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.DnsRecordResponse>("tracking", Tracking);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.DnsRecordResponse>("unsubscribe", Unsubscribe);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
