// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Helo.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SendBroadcastRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.SendBroadcastRequest_attachments>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.SendBroadcastRequest_attachments> Attachments { get; set; }
#endif
        /// <summary>The from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.MailAddress? From { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.MailAddress From { get; set; }
#endif
        /// <summary>The headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendBroadcastRequest_headers? Headers { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendBroadcastRequest_headers Headers { get; set; }
#endif
        /// <summary>The messages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.SendBroadcastRequest_messages>? Messages { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.SendBroadcastRequest_messages> Messages { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendBroadcastRequest_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendBroadcastRequest_metadata Metadata { get; set; }
#endif
        /// <summary>The replyTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.MailAddress>? ReplyTo { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.MailAddress> ReplyTo { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The template property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendBroadcastRequest_template? Template { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendBroadcastRequest_template Template { get; set; }
#endif
        /// <summary>The tracking property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendBroadcastRequest_tracking? Tracking { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendBroadcastRequest_tracking Tracking { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Models.SendBroadcastRequest"/> and sets the default values.
        /// </summary>
        public SendBroadcastRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Helo.ApiClient.Models.SendBroadcastRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Helo.ApiClient.Models.SendBroadcastRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Helo.ApiClient.Models.SendBroadcastRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.SendBroadcastRequest_attachments>(global::Helo.ApiClient.Models.SendBroadcastRequest_attachments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "from", n => { From = n.GetObjectValue<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_headers>(global::Helo.ApiClient.Models.SendBroadcastRequest_headers.CreateFromDiscriminatorValue); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.SendBroadcastRequest_messages>(global::Helo.ApiClient.Models.SendBroadcastRequest_messages.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_metadata>(global::Helo.ApiClient.Models.SendBroadcastRequest_metadata.CreateFromDiscriminatorValue); } },
                { "replyTo", n => { ReplyTo = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "template", n => { Template = n.GetObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_template>(global::Helo.ApiClient.Models.SendBroadcastRequest_template.CreateFromDiscriminatorValue); } },
                { "tracking", n => { Tracking = n.GetObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_tracking>(global::Helo.ApiClient.Models.SendBroadcastRequest_tracking.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.SendBroadcastRequest_attachments>("attachments", Attachments);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.MailAddress>("from", From);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_headers>("headers", Headers);
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.SendBroadcastRequest_messages>("messages", Messages);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_metadata>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>("replyTo", ReplyTo);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_template>("template", Template);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_tracking>("tracking", Tracking);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
