// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Helo.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SendTransactionalRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.SendTransactionalRequest_attachments>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.SendTransactionalRequest_attachments> Attachments { get; set; }
#endif
        /// <summary>The bcc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.MailAddress>? Bcc { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.MailAddress> Bcc { get; set; }
#endif
        /// <summary>The cc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.MailAddress>? Cc { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.MailAddress> Cc { get; set; }
#endif
        /// <summary>The from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.MailAddress? From { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.MailAddress From { get; set; }
#endif
        /// <summary>The headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendTransactionalRequest_headers? Headers { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendTransactionalRequest_headers Headers { get; set; }
#endif
        /// <summary>The html property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Html { get; set; }
#nullable restore
#else
        public string Html { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendTransactionalRequest_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendTransactionalRequest_metadata Metadata { get; set; }
#endif
        /// <summary>The replyTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.MailAddress>? ReplyTo { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.MailAddress> ReplyTo { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The template property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendTransactionalRequest_template? Template { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendTransactionalRequest_template Template { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.MailAddress>? To { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.MailAddress> To { get; set; }
#endif
        /// <summary>The tracking property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendTransactionalRequest_tracking? Tracking { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendTransactionalRequest_tracking Tracking { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Models.SendTransactionalRequest"/> and sets the default values.
        /// </summary>
        public SendTransactionalRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Helo.ApiClient.Models.SendTransactionalRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Helo.ApiClient.Models.SendTransactionalRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Helo.ApiClient.Models.SendTransactionalRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.SendTransactionalRequest_attachments>(global::Helo.ApiClient.Models.SendTransactionalRequest_attachments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bcc", n => { Bcc = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cc", n => { Cc = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "from", n => { From = n.GetObjectValue<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Helo.ApiClient.Models.SendTransactionalRequest_headers>(global::Helo.ApiClient.Models.SendTransactionalRequest_headers.CreateFromDiscriminatorValue); } },
                { "html", n => { Html = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Helo.ApiClient.Models.SendTransactionalRequest_metadata>(global::Helo.ApiClient.Models.SendTransactionalRequest_metadata.CreateFromDiscriminatorValue); } },
                { "replyTo", n => { ReplyTo = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "template", n => { Template = n.GetObjectValue<global::Helo.ApiClient.Models.SendTransactionalRequest_template>(global::Helo.ApiClient.Models.SendTransactionalRequest_template.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "to", n => { To = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tracking", n => { Tracking = n.GetObjectValue<global::Helo.ApiClient.Models.SendTransactionalRequest_tracking>(global::Helo.ApiClient.Models.SendTransactionalRequest_tracking.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.SendTransactionalRequest_attachments>("attachments", Attachments);
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>("bcc", Bcc);
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>("cc", Cc);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.MailAddress>("from", From);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendTransactionalRequest_headers>("headers", Headers);
            writer.WriteStringValue("html", Html);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendTransactionalRequest_metadata>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>("replyTo", ReplyTo);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendTransactionalRequest_template>("template", Template);
            writer.WriteStringValue("text", Text);
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>("to", To);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendTransactionalRequest_tracking>("tracking", Tracking);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
