// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Helo.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SendBroadcastRequest_messages : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bcc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.MailAddress>? Bcc { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.MailAddress> Bcc { get; set; }
#endif
        /// <summary>The cc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.MailAddress>? Cc { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.MailAddress> Cc { get; set; }
#endif
        /// <summary>Model used for template placeholder replacement</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendBroadcastRequest_messages_data? Data { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendBroadcastRequest_messages_data Data { get; set; }
#endif
        /// <summary>The headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendBroadcastRequest_messages_headers? Headers { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendBroadcastRequest_messages_headers Headers { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.SendBroadcastRequest_messages_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.SendBroadcastRequest_messages_metadata Metadata { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.MailAddress>? To { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.MailAddress> To { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Models.SendBroadcastRequest_messages"/> and sets the default values.
        /// </summary>
        public SendBroadcastRequest_messages()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Helo.ApiClient.Models.SendBroadcastRequest_messages"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Helo.ApiClient.Models.SendBroadcastRequest_messages CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Helo.ApiClient.Models.SendBroadcastRequest_messages();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bcc", n => { Bcc = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cc", n => { Cc = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "data", n => { Data = n.GetObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_messages_data>(global::Helo.ApiClient.Models.SendBroadcastRequest_messages_data.CreateFromDiscriminatorValue); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_messages_headers>(global::Helo.ApiClient.Models.SendBroadcastRequest_messages_headers.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_messages_metadata>(global::Helo.ApiClient.Models.SendBroadcastRequest_messages_metadata.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "to", n => { To = n.GetCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>(global::Helo.ApiClient.Models.MailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>("bcc", Bcc);
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>("cc", Cc);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_messages_data>("data", Data);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_messages_headers>("headers", Headers);
            writer.WriteObjectValue<global::Helo.ApiClient.Models.SendBroadcastRequest_messages_metadata>("metadata", Metadata);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteCollectionOfObjectValues<global::Helo.ApiClient.Models.MailAddress>("to", To);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
