// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Helo.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Statistics : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bounced property</summary>
        public int? Bounced { get; set; }
        /// <summary>The clicked property</summary>
        public int? Clicked { get; set; }
        /// <summary>The complained property</summary>
        public int? Complained { get; set; }
        /// <summary>The delivered property</summary>
        public int? Delivered { get; set; }
        /// <summary>The opened property</summary>
        public int? Opened { get; set; }
        /// <summary>The sent property</summary>
        public int? Sent { get; set; }
        /// <summary>The unsubscribed property</summary>
        public int? Unsubscribed { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Models.Statistics"/> and sets the default values.
        /// </summary>
        public Statistics()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Helo.ApiClient.Models.Statistics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Helo.ApiClient.Models.Statistics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Helo.ApiClient.Models.Statistics();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bounced", n => { Bounced = n.GetIntValue(); } },
                { "clicked", n => { Clicked = n.GetIntValue(); } },
                { "complained", n => { Complained = n.GetIntValue(); } },
                { "delivered", n => { Delivered = n.GetIntValue(); } },
                { "opened", n => { Opened = n.GetIntValue(); } },
                { "sent", n => { Sent = n.GetIntValue(); } },
                { "unsubscribed", n => { Unsubscribed = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bounced", Bounced);
            writer.WriteIntValue("clicked", Clicked);
            writer.WriteIntValue("complained", Complained);
            writer.WriteIntValue("delivered", Delivered);
            writer.WriteIntValue("opened", Opened);
            writer.WriteIntValue("sent", Sent);
            writer.WriteIntValue("unsubscribed", Unsubscribed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
