// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Helo.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebhookEndpointResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The additionalHeaders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Helo.ApiClient.Models.WebhookEndpointResponse_additionalHeaders? AdditionalHeaders { get; set; }
#nullable restore
#else
        public global::Helo.ApiClient.Models.WebhookEndpointResponse_additionalHeaders AdditionalHeaders { get; set; }
#endif
        /// <summary>The channelId property</summary>
        public Guid? ChannelId { get; set; }
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The events property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Helo.ApiClient.Models.WebhookEventsTrigger?>? Events { get; set; }
#nullable restore
#else
        public List<global::Helo.ApiClient.Models.WebhookEventsTrigger?> Events { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The payloadSigningKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayloadSigningKey { get; set; }
#nullable restore
#else
        public string PayloadSigningKey { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Helo.ApiClient.Models.WebhookEndpointResponse"/> and sets the default values.
        /// </summary>
        public WebhookEndpointResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Helo.ApiClient.Models.WebhookEndpointResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Helo.ApiClient.Models.WebhookEndpointResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Helo.ApiClient.Models.WebhookEndpointResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalHeaders", n => { AdditionalHeaders = n.GetObjectValue<global::Helo.ApiClient.Models.WebhookEndpointResponse_additionalHeaders>(global::Helo.ApiClient.Models.WebhookEndpointResponse_additionalHeaders.CreateFromDiscriminatorValue); } },
                { "channelId", n => { ChannelId = n.GetGuidValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "events", n => { Events = n.GetCollectionOfEnumValues<global::Helo.ApiClient.Models.WebhookEventsTrigger>()?.AsList(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "payloadSigningKey", n => { PayloadSigningKey = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Helo.ApiClient.Models.WebhookEndpointResponse_additionalHeaders>("additionalHeaders", AdditionalHeaders);
            writer.WriteGuidValue("channelId", ChannelId);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteCollectionOfEnumValues<global::Helo.ApiClient.Models.WebhookEventsTrigger>("events", Events);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("payloadSigningKey", PayloadSigningKey);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
