// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Helo.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WebhookEventsTrigger
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "accepted")]
        #pragma warning disable CS1591
        Accepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "processed")]
        #pragma warning disable CS1591
        Processed,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounced")]
        #pragma warning disable CS1591
        Bounced,
        #pragma warning restore CS1591
        [EnumMember(Value = "opened")]
        #pragma warning disable CS1591
        Opened,
        #pragma warning restore CS1591
        [EnumMember(Value = "clicked")]
        #pragma warning disable CS1591
        Clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "reported-spam")]
        #pragma warning disable CS1591
        ReportedSpam,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription-changed")]
        #pragma warning disable CS1591
        SubscriptionChanged,
        #pragma warning restore CS1591
        [EnumMember(Value = "channel-suspended")]
        #pragma warning disable CS1591
        ChannelSuspended,
        #pragma warning restore CS1591
        [EnumMember(Value = "channel-high-bounce-rate")]
        #pragma warning disable CS1591
        ChannelHighBounceRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "channel-high-spam-rate")]
        #pragma warning disable CS1591
        ChannelHighSpamRate,
        #pragma warning restore CS1591
    }
}
